### PR TITLE
HW1 committed for review

### PR DESCRIPTION
**Pull request by gleason9113**
01-selectors.md
-Added answers for each level of CSS Diner.

01-palindrome.html
-Formatted the form to match the homework example using Bootstrap containers and classes.

02-palindrome.js
-Implemented the handleInput function.
--Validate numeric, non-negative input
--Verify palindrome quality
--Add output to HTML element.

Requested feedback:
CSS/Bootstrap is a weak area for me; feedback is appreciated! Other suggestions are of course also welcome.

### CODE REVIEW

**Review by rfilgas — APPROVED** [review]
There's a few style choices differing from the airbnb style guide. I would recommend getting eslint set up with their config and you can use it to auto-format.

Screenshot 2023-04-10 at 9 25 10 PM

After the auto-format there were only two errors remaining, so setting up the linter might be the easiest solution.

Screenshot 2023-04-10 at 9 28 28 PM

Style wise  as a personal preference you could rename your variables to reduce the need for comments. reverse could be named reversedInput.' numCheck' could be renamed 'isANumber' etc.

The code is nicely concise overall, good job. I don't have a ton to say about CSS as I'm in the same boat as you there. I still have a lot to learn.

**Comment by gleason9113** [comment]
Honestly, I thought I had configured Prettier with the airbnb format correctly.  I need to dig deeper into that and see what I did wrong.
Changes:

02-palindrome.js
-Addressed style issue:  Moved handleInput definition above the function call.
-Addressed style issue:  Added spaces after comments.
-Addressed style issue:  Added space on line 18 after 'if'.
-Addressed style issue:  Added regular literal instead of regex constructor.
-Addressed style issue:  Clarified non-numeric/negative value error.

Edit:  Updated list of changes.

**Comment by rfilgas** [comment]
> 

There's no way to override prettier with the airbnb eslint configuration where there are conflicts, you can only dump air bnb's settings to accept prettier's natively. It's not a very good move on the apps part as there's no way to see every case in which the rules conflict to change prettier's configuration file. Prettier has unfortunately left this up to clunky add ons to run an eslint --fix after the fact. It's unfortunate that it can't just accept overrides from an eslintrc file to set up the default config.

My recommendation right now is to run prettier and then eslint after or set up one of the tools they talk about that will run them sequentially. Docs below:

[integrating-prettier-with-linters](https://prettier.io/docs/en/integrating-with-linters.html)

**Review by Rajashree-Pethkar — APPROVED** [review]
Everything looks fine. Most of the reviews were already addressed.

**Pull request merged**
